# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADVENTURE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNo', models.IntegerField()),
                ('Gender', models.CharField(max_length=64)),
                ('City_Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GYM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TraineeName', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNo', models.IntegerField()),
                ('Gender', models.CharField(max_length=64)),
                ('City_Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MEDITATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNo', models.IntegerField()),
                ('Gender', models.CharField(max_length=64)),
                ('City_Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNo', models.IntegerField()),
                ('Gender', models.CharField(max_length=64)),
            ],
        ),
    ]
