# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_adventure_gym_meditation_yoga'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRANIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNo', models.IntegerField()),
                ('Gender', models.CharField(max_length=64)),
                ('City_Name', models.CharField(max_length=64)),
            ],
        ),
    ]
